# Generated by Django 5.1.2 on 2024-11-03 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, null=True, verbose_name='Дата публикации')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='product.category', verbose_name='Родитель категории')),
            ],
            options={
                'verbose_name': 'Об институте',
                'verbose_name_plural': 'Об институте',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': '2. Подкатегория',
                'verbose_name_plural': '2. Подкатегория',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.category',),
        ),
        migrations.CreateModel(
            name='TopLevelCategory',
            fields=[
            ],
            options={
                'verbose_name': '1. Основная категория',
                'verbose_name_plural': '1. Основная категория',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('product.category',),
        ),
    ]
