# Generated by Django 5.1.2 on 2024-11-03 18:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '3. Продукт', 'verbose_name_plural': '3. Продукт'},
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Краткое описание'),
        ),
    ]
