# Generated by Django 5.1.2 on 2024-11-03 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_discount_price_product_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '4. Комментарий', 'verbose_name_plural': '4. Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '5. Отзыв', 'verbose_name_plural': '5. Отзывы'},
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг'),
        ),
    ]
