# Generated by Django 5.1.2 on 2024-11-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='outer_diameter_of_the_head',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Внешний диаметр головки (мм)'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Размер'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_of_brackets',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Размер скоб'),
        ),
        migrations.AddField(
            model_name='product',
            name='the_height_of_the_closing_barckets',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Высота закрытия скобок'),
        ),
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Объём'),
        ),
    ]
