# Generated by Django 5.1.2 on 2024-11-16 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_orderproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': '6 Заказанный продукт', 'verbose_name_plural': '6 Заказанные продукты'},
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=250, null=True, verbose_name='Размер')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Размер продукта',
                'verbose_name_plural': 'Размер продукта',
            },
        ),
    ]
