# Generated by Django 5.1.2 on 2024-11-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_orderproduct_options_productsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.JSONField(blank=True, null=True, verbose_name='Размер'),
        ),
    ]
