# Generated by Django 5.1.2 on 2024-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productsize_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='size',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Размер'),
        ),
    ]
