# Generated by Django 5.1.2 on 2024-11-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Изображения для карусели баннеров',
                'verbose_name_plural': 'Изображения для карусели баннеров',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GetConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250, verbose_name='Полное имя')),
                ('phone', models.CharField(max_length=250, verbose_name='Телефон')),
                ('msg', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Пришла на консультацию',
                'verbose_name_plural': 'Пришла на консультацию',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner/', verbose_name='Логотип для партнеров')),
            ],
            options={
                'verbose_name': 'Наши партнеры',
                'verbose_name_plural': 'Наши партнеры',
                'ordering': ['id'],
            },
        ),
    ]
